server {

    listen 80;

    server_name localhost;



    root /usr/share/nginx/html;

    index index.html;



    location / {

        try_files $uri /index.html;

    }



    location /stream {

        proxy_pass http://backend:8080/stream;

        proxy_http_version 1.1;

        proxy_set_header Connection '';

        proxy_buffering off;

        proxy_cache off;

        proxy_read_timeout 86400s;

    }



    location /audit/stream {

        proxy_pass http://audit:8081/audit/stream;

        proxy_http_version 1.1;

        proxy_set_header Connection '';

        proxy_buffering off;

        proxy_cache off;

        proxy_read_timeout 86400s;

    }



    location /audit/ {

        proxy_pass http://audit:8081/audit/;

    }

}

